#backend/migrations/versions/c39856f923f6_create_tickets_table.py
"""create tickets table

Revision ID: c39856f923f6
Revises: 090b8c342d52
Create Date: 2025-09-06 04:34:12.751596+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c39856f923f6'
down_revision: Union[str, None] = '090b8c342d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_id')
        batch_op.create_index(batch_op.f('ix_users_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_users_email'))
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=1)

    # ### end Alembic commands ###
